"""Core-AI course supply contracts for future recommendation consumers."""

from app.course_catalog.openedx import (
    OpenEdxCourseProvider,
    OpenEdxProviderError,
    to_normalized_candidate,
)
from app.course_catalog.schemas import (
    CourseAvailability,
    CourseCapability,
    CourseCapabilityProfile,
    CoursePrerequisite,
    CourseProfileStatus,
    CourseProvenance,
    CourseSourceType,
    CoverageType,
    ExternalCourse,
    NormalizedCourseCandidate,
)
from app.course_catalog.semantic_enrichment import (
    ENRICHMENT_POLICY_VERSION,
    ClaimReviewStatus,
    CourseCapabilityClaimProposal,
    CourseSemanticEvidence,
    EvidenceStrength,
    MappingMethod,
    MetadataSufficiency,
    RejectionReason,
    build_draft_profile,
    metadata_sufficiency,
    review_claim,
)
from app.course_catalog.skillscommons import (
    SkillsCommonsAccessStatus,
    SkillsCommonsBitstreamType,
    SkillsCommonsCourseProvider,
    SkillsCommonsDspaceBitstream,
    SkillsCommonsDspaceBundle,
    SkillsCommonsDspaceItem,
    SkillsCommonsLearningAccess,
    SkillsCommonsLicenseStatus,
    SkillsCommonsLiveSample,
    SkillsCommonsMaterialType,
    SkillsCommonsProviderError,
)
from app.course_catalog.skillscommons import (
    to_normalized_candidate as skillscommons_to_normalized_candidate,
)

__all__ = [
    "CourseAvailability",
    "CourseCapability",
    "CourseCapabilityProfile",
    "CoursePrerequisite",
    "CourseProfileStatus",
    "CourseProvenance",
    "CourseSourceType",
    "CoverageType",
    "ExternalCourse",
    "NormalizedCourseCandidate",
    "ENRICHMENT_POLICY_VERSION",
    "ClaimReviewStatus",
    "CourseCapabilityClaimProposal",
    "CourseSemanticEvidence",
    "EvidenceStrength",
    "MappingMethod",
    "MetadataSufficiency",
    "RejectionReason",
    "build_draft_profile",
    "metadata_sufficiency",
    "review_claim",
    "OpenEdxCourseProvider",
    "OpenEdxProviderError",
    "to_normalized_candidate",
    "SkillsCommonsAccessStatus",
    "SkillsCommonsBitstreamType",
    "SkillsCommonsCourseProvider",
    "SkillsCommonsDspaceBitstream",
    "SkillsCommonsDspaceBundle",
    "SkillsCommonsDspaceItem",
    "SkillsCommonsLiveSample",
    "SkillsCommonsLearningAccess",
    "SkillsCommonsLicenseStatus",
    "SkillsCommonsMaterialType",
    "SkillsCommonsProviderError",
    "skillscommons_to_normalized_candidate",
]
