"""Provider-neutral contracts for governed capability identity."""

from app.capability_governance.definitions import (
    CapabilityDefinition,
    CapabilityDefinitionStatus,
    CapabilityDeprecationRecord,
    deprecate_capability_definition,
)
from app.capability_governance.errors import (
    ActivationGateError,
    CapabilityGovernanceError,
    CapabilityNotActiveError,
    ChecksumMismatchError,
    DependencyCycleError,
    DependencyNotActiveError,
    DuplicateCapabilityError,
    DuplicateReleaseError,
    InvalidLifecycleTransitionError,
    NamespaceConflictError,
    PackNotActiveError,
    ReleaseNotFoundError,
    UnknownCapabilityError,
    UnknownNamespaceError,
)
from app.capability_governance.identity import (
    CanonicalCapabilityRef,
    CapabilityIdentityPair,
    SourceSemanticKind,
    SourceSemanticRef,
)
from app.capability_governance.packs import (
    CapabilityGovernanceDecision,
    CapabilityGovernanceReview,
    CapabilityPackDependency,
    CapabilityPackId,
    CapabilityPackRelease,
    CapabilityPackReleaseRef,
    CapabilityPackStatus,
    CapabilityReleaseApproval,
    activate_capability_pack_release,
    build_capability_pack_release,
    compute_release_checksum,
    deprecate_capability_pack_release,
)
from app.capability_governance.resolution import (
    CapabilityDefinitionPin,
    resolve_for_new_binding,
    resolve_historical,
)

__all__ = [
    "CanonicalCapabilityRef",
    "CapabilityIdentityPair",
    "SourceSemanticKind",
    "SourceSemanticRef",
    "CapabilityDefinition",
    "CapabilityDefinitionStatus",
    "CapabilityDeprecationRecord",
    "deprecate_capability_definition",
    "CapabilityGovernanceError",
    "ActivationGateError",
    "CapabilityNotActiveError",
    "ChecksumMismatchError",
    "DependencyCycleError",
    "DependencyNotActiveError",
    "DuplicateCapabilityError",
    "DuplicateReleaseError",
    "InvalidLifecycleTransitionError",
    "NamespaceConflictError",
    "PackNotActiveError",
    "ReleaseNotFoundError",
    "UnknownCapabilityError",
    "UnknownNamespaceError",
    "CapabilityGovernanceDecision",
    "CapabilityGovernanceReview",
    "CapabilityPackDependency",
    "CapabilityPackId",
    "CapabilityPackRelease",
    "CapabilityPackReleaseRef",
    "CapabilityPackStatus",
    "CapabilityReleaseApproval",
    "activate_capability_pack_release",
    "build_capability_pack_release",
    "compute_release_checksum",
    "deprecate_capability_pack_release",
    "CapabilityDefinitionPin",
    "resolve_for_new_binding",
    "resolve_historical",
]
